# Generated by Django 5.0.6 on 2024-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('expire_date', models.DateTimeField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
