# Generated by Django 5.0.6 on 2024-07-12 08:21

import django.db.models.deletion
import shortuuid.django_fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='cat-', unique=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', max_length=250, upload_to='')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConpetenceTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='job-', unique=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', max_length=250, upload_to='')),
                ('description', models.TextField()),
                ('requierements', models.TextField(default='')),
                ('responsability', models.TextField(default='')),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.CharField(default='A en discuter', max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('qualification', models.CharField(default='aucun diplome requis', max_length=150)),
                ('locality', models.CharField(max_length=50)),
                ('genre', models.CharField(default='', max_length=50)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('facebook_link', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('instagram_link', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('twetter_link', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('youtube_link', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('mail', models.EmailField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.profileemployeur')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='post.category')),
                ('competence', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='post.ConpetenceTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='conpetencetaggeditem',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.job'),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='post.job')),
            ],
        ),
        migrations.CreateModel(
            name='TagTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.job')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='post.TagTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
