# Generated by Django 5.0.6 on 2024-07-12 08:26

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=255, prefix='cat-', unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=255, prefix='job-', unique=True),
        ),
    ]
