# Generated by Django 5.0.6 on 2024-07-04 18:19

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_job_jid'),
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='cat-', unique=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', max_length=250, upload_to='')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.profileemployeur'),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=250, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='post.category'),
        ),
    ]
