# Generated by Django 5.0.6 on 2024-07-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_category_cid_alter_job_jid'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='post.job'),
        ),
    ]
