# Generated by Django 5.0.6 on 2024-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_locality_address_alter_locality_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['job', 'latitude', 'longitude'], 'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
        migrations.AddField(
            model_name='locality',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
