# Generated by Django 5.0.6 on 2024-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_experience_job_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
