# Generated by Django 5.0.6 on 2024-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_job_icon_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='A en discuter', max_length=100),
        ),
    ]
