# Generated by Django 5.0.6 on 2024-07-05 13:18

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_category_icon_job_salary'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='competence',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
