# Generated by Django 5.0.6 on 2024-07-05 13:46

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_job_competence'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='facebook_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='instagram_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='aucun diplome requis', max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='twetter_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='youtube_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.RemoveField(
            model_name='job',
            name='tag',
        ),
        migrations.CreateModel(
            name='ConpetenceTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.job')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='competence',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='post.ConpetenceTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TagTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.job')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='post.TagTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
