# Generated by Django 5.0.6 on 2024-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_job_facebook_link_job_genre_job_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requierements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='responsability',
            field=models.TextField(default=''),
        ),
    ]
