# Generated by Django 5.0.6 on 2024-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_job_requierements_job_responsability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='twetter_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
