# Generated by Django 5.0.6 on 2024-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_job_facebook_link_alter_job_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='facebook_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='instagram_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='twetter_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='youtube_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
    ]
