# Generated by Django 5.0.6 on 2024-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_job_facebook_link_alter_job_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
