# Generated by Django 5.0.6 on 2024-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_job_mail_job_phone_job_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
