# Generated by Django 5.0.6 on 2024-07-12 08:20

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEmployeur',
            fields=[
                ('eid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
