# Generated by Django 5.0.6 on 2024-07-04 16:01

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileemployeur',
            name='id',
        ),
        migrations.AddField(
            model_name='profileemployeur',
            name='eid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=20, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./def ault.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=20, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
