# Generated by Django 5.0.6 on 2024-07-12 08:26

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileemployeur',
            name='eid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=20, max_length=255, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
