# Generated by Django 5.0.6 on 2024-07-04 17:58

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profileemployeur_id_profileemployeur_eid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='User-', unique=True),
        ),
    ]
