# Generated by Django 5.0.6 on 2024-07-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileemployeur',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
